language: python
python:
  #- "2.7"
  #- "3.3"
  # - "3.4"
  # - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip list
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip list
# command to run tests
script:
  - pytest  -s -v --cov --cov-report term-missing
after_success:
  coveralls